import { defineRecipe as r } from "./recipe-helpers";

// Original household versions. Sources explain the dishes and their many variations.
const region = "West Africa" as const;
export const westAfricanRecipes = [
  r({
    id: "nigerian-jollof",
    name: "Nigerian jollof rice",
    subtitle: "Pepper-rich rice, gently steamed in a tomato base.",
    cuisine: "Nigeria",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 60,
    restTime: 10,
    restLabel: "Rest",
    illustration: "rice",
    ingredients: [
      ["Long-grain parboiled rice", "350 g", "Pantry"],
      ["Chopped tomatoes", "400 g can", "Pantry"],
      ["Red peppers", "2", "Produce"],
      ["Onions", "2", "Produce"],
      ["Tomato paste", "3 tbsp", "Pantry"],
      ["Vegetable oil", "4 tbsp", "Pantry"],
      ["Vegetable stock", "400 ml, plus extra if needed", "Pantry"],
      ["Curry powder", "1 tsp", "Pantry"],
      ["Dried thyme", "1 tsp", "Pantry"],
      ["Bay leaves", "2", "Pantry"],
      ["Scotch bonnet", "½, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Rinse the rice and drain. Blend tomatoes, peppers, one onion and optional chilli; finely slice the other onion.",
      "Heat oil in a heavy pot over medium heat. Soften the sliced onion for 5 minutes, then stir in tomato paste for 3 minutes.",
      "Add the blend. Cook uncovered for 15–20 minutes, stirring, until thick rather than watery.",
      "Stir in curry powder, thyme, bay, rice and hot stock. Taste the liquid for salt, then bring to a gentle simmer.",
      "Cover tightly and turn the heat very low. Cook for 25–30 minutes. If grains are still hard and the pot is dry, add 50 ml hot water and cover for 5 more minutes.",
      "Rest off the heat, covered, for 10 minutes. Remove bay leaves and lift the rice gently with a fork.",
    ],
    servingSuggestion:
      "Serve with cucumber salad, fried plantain or grilled chicken.",
    tips: [
      "Rice brands vary; add extra liquid a little at a time.",
      "Leave out the Scotch bonnet for a mild family pot.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · jollof",
      url: "https://cheflolaskitchen.com/jollof-rice/",
    },
  }),
  r({
    id: "ghanaian-jollof",
    name: "Ghanaian-style jollof",
    subtitle: "A fragrant jasmine-rice version with ginger and warm spices.",
    cuisine: "Ghana",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 50,
    restTime: 10,
    restLabel: "Rest",
    illustration: "rice",
    ingredients: [
      ["Jasmine rice", "350 g", "Pantry"],
      ["Tomatoes", "400 g", "Produce"],
      ["Red peppers", "1", "Produce"],
      ["Onions", "2", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Fresh ginger", "20 g", "Produce"],
      ["Tomato paste", "3 tbsp", "Pantry"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Vegetable stock", "350 ml, plus extra if needed", "Pantry"],
      ["Curry powder", "1 tsp", "Pantry"],
      ["Ground nutmeg", "⅛ tsp", "Pantry"],
      ["Bay leaves", "1", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Rinse and drain rice. Blend tomatoes, pepper, one onion, garlic and ginger until smooth. Slice the remaining onion.",
      "Heat oil in a heavy saucepan. Cook sliced onion for 5 minutes; add tomato paste and stir for 3 minutes.",
      "Pour in the blended vegetables. Simmer uncovered for 15 minutes, stirring frequently, until reduced and thick.",
      "Add curry powder, nutmeg, bay leaf, rice and hot stock. Stir once, taste for salt and bring to a simmer.",
      "Cover tightly and cook on the lowest heat for 20–25 minutes. Check a grain; if firm, add a small splash of boiling water and cook covered a little longer.",
      "Leave covered off the heat for 10 minutes. Remove the bay leaf and gently fluff.",
    ],
    servingSuggestion: "Pair with beans, a simple salad or grilled fish.",
    tips: [
      "This is a meat-free household adaptation; Ghanaian jollof has many family variations.",
      "Jasmine rice needs less liquid and gentler handling than parboiled rice.",
    ],
    source: {
      name: "Immaculate Bites · Ghana jollof",
      url: "https://www.africanbites.com/ghana-jollof-rice/",
    },
  }),
  r({
    id: "red-red",
    name: "Red red & plantain",
    subtitle: "Ghanaian black-eyed beans with a rich tomato sauce.",
    cuisine: "Ghana",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 30,
    illustration: "stew",
    ingredients: [
      ["Black-eyed beans", "2 × 400 g cans", "Pantry"],
      ["Ripe plantains", "2 large", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Fresh ginger", "15 g", "Produce"],
      ["Chopped tomatoes", "400 g can", "Pantry"],
      ["Tomato paste", "1 tbsp", "Pantry"],
      ["Red palm oil", "3 tbsp", "Pantry"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Chilli flakes", "¼ tsp, optional", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Drain and rinse the beans. Dice the onion, mince garlic and grate ginger. Peel plantains and cut into 1 cm diagonal slices.",
      "Warm palm oil over medium heat without smoking it. Cook onion for 5 minutes, then garlic, ginger and tomato paste for 2 minutes.",
      "Add tomatoes and optional chilli. Simmer for 12 minutes until the sauce thickens, stirring to prevent sticking.",
      "Fold in beans and 150 ml water. Simmer gently for 10 minutes; mash a spoonful of beans to thicken. Taste for salt.",
      "Meanwhile heat vegetable oil in a wide frying pan. Fry plantain in batches for 3–4 minutes per side until golden and tender.",
      "Drain plantain on kitchen paper and divide between plates with the beans.",
    ],
    servingSuggestion: "A complete light meal; add rice for bigger appetites.",
    tips: [
      "Canned beans make this a weeknight version.",
      "Red palm oil gives its characteristic flavour; vegetable oil works but changes the dish.",
    ],
    source: {
      name: "Immaculate Bites · red red",
      url: "https://www.africanbites.com/red-redafrican-stewed-black-eyed-peas/",
    },
  }),
  r({
    id: "waakye",
    name: "Waakye rice & beans",
    subtitle: "A Ghanaian staple coloured with food-grade sorghum leaves.",
    cuisine: "Ghana",
    region,
    diet: "Plant-based",
    prepTime: 10,
    cookTime: 80,
    restTime: 480,
    restLabel: "Soak beans",
    illustration: "rice",
    ingredients: [
      ["Dried black-eyed beans", "200 g", "Pantry"],
      ["Long-grain rice", "300 g", "Pantry"],
      ["Food-grade waakye leaves", "4–6 dried sorghum leaves", "Pantry"],
      ["Salt", "1 tsp, or to taste", "Pantry"],
    ],
    steps: [
      "Sort and rinse beans. Cover generously with cold water and soak in the fridge for 8 hours, then drain.",
      "Rinse waakye leaves. Place in a pot with beans and 1 litre fresh water. Bring to the boil, then simmer for 35–50 minutes until beans are almost tender.",
      "Remove leaves with tongs. Drain beans over a jug, keeping the coloured liquid. Return beans to the pot.",
      "Rinse rice and add to the beans. Measure 550 ml reserved cooking liquid, topping up with hot water if needed, and add with salt.",
      "Bring to a simmer, cover and cook on low for 20–25 minutes, until rice is tender. Add small splashes of hot water only if needed.",
      "Turn off the heat, leave covered for 10 minutes and fluff gently.",
    ],
    servingSuggestion:
      "Serve with tomato stew, avocado, shito or a boiled egg, adding those extras to your shopping list.",
    tips: [
      "Use leaves sold for cooking, not ornamental sorghum.",
      "Without the leaves you can still make rice and beans, but the characteristic colour and taste change.",
    ],
    source: {
      name: "Eat Well Abi · waakye",
      url: "https://eatwellabi.com/fast-easy-ghanaian-waakye-recipe/",
    },
  }),
  r({
    id: "kelewele",
    name: "Kelewele spiced plantain",
    subtitle: "Ginger-seasoned golden plantain for sharing.",
    cuisine: "Ghana",
    region,
    diet: "Plant-based",
    category: "Side dish",
    prepTime: 10,
    cookTime: 20,
    restTime: 10,
    restLabel: "Marinate",
    illustration: "tray",
    ingredients: [
      ["Ripe plantains", "4", "Produce"],
      ["Fresh ginger", "25 g", "Produce"],
      ["Onions", "½ small", "Produce"],
      ["Cayenne pepper", "¼ tsp, or to taste", "Pantry"],
      ["Ground cloves", "⅛ tsp", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
      ["Vegetable oil", "250 ml, for shallow frying", "Pantry"],
    ],
    steps: [
      "Choose yellow plantains with some dark spots, still firm enough to cut. Peel and cut into 2 cm pieces.",
      "Finely grate ginger and onion into a bowl. Mix with cayenne, cloves and salt; avoid adding water.",
      "Toss plantain through the seasoning and leave for 10 minutes.",
      "Pour oil about 1 cm deep into a sturdy pan. Heat to roughly 175°C; it should be hot but not smoking.",
      "Fry in small batches, turning regularly, for 6–8 minutes until golden outside and soft through the middle. Lower heat if spices darken too quickly.",
      "Lift with a slotted spoon and drain on kitchen paper. Serve hot while the edges are crisp.",
    ],
    servingSuggestion:
      "Serves four as a side with red red, jollof or grilled fish.",
    tips: [
      "For a milder version, leave out cayenne and keep the ginger.",
      "Overripe plantains soften and absorb more oil; use them for tatale instead.",
    ],
    source: {
      name: "Immaculate Bites · kelewele",
      url: "https://www.africanbites.com/kelewele-or-alocospicy-fried-plantains/",
    },
  }),
  r({
    id: "groundnut-soup",
    name: "Chicken groundnut soup",
    subtitle: "A Ghanaian-style peanut soup with tomato and ginger.",
    cuisine: "Ghana",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 50,
    ingredients: [
      ["Boneless chicken thighs", "600 g", "Meat & fish"],
      ["Unsweetened peanut butter", "150 g", "Pantry"],
      ["Tomatoes", "3", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Fresh ginger", "20 g", "Produce"],
      ["Tomato paste", "1 tbsp", "Pantry"],
      ["Chicken stock", "900 ml", "Pantry"],
      ["Scotch bonnet", "1, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Cut chicken into large pieces. Blend tomatoes, onion, garlic and ginger with 100 ml of the stock.",
      "Put chicken, blended vegetables and tomato paste in a deep pot. Bring to a simmer and cook for 10 minutes, stirring occasionally.",
      "Whisk peanut butter with 300 ml warm stock in a bowl until smooth and pour into the pot.",
      "Add remaining stock and optional whole chilli. Bring back to a gentle simmer, then partially cover.",
      "Cook for 35–40 minutes, stirring the bottom often so the peanuts do not catch. Chicken must reach 74°C in its thickest piece.",
      "Remove chilli without bursting it. Adjust salt and add hot water for a pourable soup consistency.",
    ],
    servingSuggestion:
      "Serve with rice or omo tuo rice balls; these are extra to the soup ingredients.",
    tips: [
      "Use unsweetened smooth peanut butter; peanuts are essential here.",
      "Keep heat gentle once the peanut butter goes in.",
    ],
    source: {
      name: "Eat Well Abi · groundnut soup",
      url: "https://eatwellabi.com/west-african-peanut-soup-recipe/",
    },
  }),
  r({
    id: "tatale",
    name: "Tatale plantain pancakes",
    subtitle: "Savoury Ghanaian pancakes made with very ripe plantain.",
    cuisine: "Ghana",
    region,
    diet: "Plant-based",
    category: "Breakfast",
    prepTime: 15,
    cookTime: 20,
    illustration: "breakfast",
    ingredients: [
      ["Very ripe plantains", "3 large", "Produce"],
      ["Fine cornmeal", "75 g", "Pantry"],
      ["Plain flour", "40 g", "Pantry"],
      ["Onions", "½ small", "Produce"],
      ["Fresh ginger", "15 g", "Produce"],
      ["Chilli powder", "¼ tsp, optional", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
      ["Vegetable oil", "4 tbsp", "Pantry"],
    ],
    steps: [
      "Peel plantains and mash thoroughly with a fork until almost smooth. Finely grate onion and ginger.",
      "Mix the onion, ginger, cornmeal, flour, salt and optional chilli into the plantain.",
      "Leave for 5 minutes while a wide non-stick pan warms over medium heat. The batter should drop slowly from a spoon.",
      "Add a tablespoon of oil. Spoon in small portions of batter and flatten into thin 7 cm rounds, leaving room to turn them.",
      "Cook for 3–4 minutes per side until browned and set through the centre. Reduce heat if they colour before cooking inside.",
      "Repeat in batches with remaining oil. Transfer to a rack or kitchen paper and serve warm.",
    ],
    servingSuggestion:
      "Makes about 12 small pancakes; serve with beans for breakfast or lunch.",
    tips: [
      "Very ripe, dark-skinned plantains give the best sweetness and texture.",
      "If batter is too loose, stir in another tablespoon of cornmeal.",
    ],
    source: {
      name: "Immaculate Bites · tatale",
      url: "https://www.africanbites.com/tatale-african-plantain-pancakes/",
    },
  }),
  r({
    id: "egusi-soup",
    name: "Egusi & spinach soup",
    subtitle: "Nigerian melon-seed soup with tender beef and leafy greens.",
    cuisine: "Nigeria",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 110,
    illustration: "greens",
    ingredients: [
      ["Stewing beef", "400 g", "Meat & fish"],
      ["Ground egusi seeds", "180 g", "Pantry"],
      ["Spinach", "300 g", "Produce"],
      ["Onions", "2", "Produce"],
      ["Red peppers", "2", "Produce"],
      ["Red palm oil", "4 tbsp", "Pantry"],
      ["Ground dried crayfish", "1 tbsp", "Meat & fish"],
      ["Beef stock", "900 ml", "Pantry"],
      ["Scotch bonnet", "½, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Cut beef into 2 cm cubes. Simmer with half a chopped onion and stock for 50–60 minutes, until tender. Keep meat and liquid.",
      "Blend peppers, remaining onion and optional chilli. Mix ground egusi with 100 ml water into a thick paste.",
      "Warm palm oil in a second pot on medium. Add pepper blend and cook for 12–15 minutes, stirring, until reduced.",
      "Add crayfish, beef and 500 ml of its cooking stock. Bring to a gentle simmer.",
      "Drop spoonfuls of egusi paste into the liquid. Cover and cook gently for 20–25 minutes, loosening the bottom carefully if it sticks.",
      "Stir in washed, chopped spinach. Simmer for 5 minutes; loosen with remaining stock and adjust salt.",
    ],
    servingSuggestion:
      "Serve with eba, pounded yam or rice, prepared separately.",
    tips: [
      "Egusi is sold ground in African food shops; pumpkin seeds give a different flavour.",
      "This version contains shellfish from dried crayfish.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · egusi",
      url: "https://cheflolaskitchen.com/egusi-soup-recipe/",
    },
  }),
  r({
    id: "efo-riro",
    name: "Efo riro with smoked fish",
    subtitle: "A Yoruba-style pepper and spinach stew.",
    cuisine: "Nigeria",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 35,
    illustration: "greens",
    ingredients: [
      ["Spinach", "700 g", "Produce"],
      ["Smoked mackerel", "250 g, skin and bones removed", "Meat & fish"],
      ["Red peppers", "3", "Produce"],
      ["Onions", "2", "Produce"],
      ["Red palm oil", "4 tbsp", "Pantry"],
      ["Ground dried crayfish", "1 tbsp", "Meat & fish"],
      ["Iru (fermented locust beans)", "1 tbsp, optional", "Pantry"],
      ["Scotch bonnet", "½, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Wash spinach, blanch in boiling water for 1 minute and cool under running water. Squeeze well and roughly chop.",
      "Pulse peppers, one onion and optional chilli into a coarse mixture. Finely slice the other onion.",
      "Warm palm oil over medium heat. Fry sliced onion for 5 minutes; add iru if using and cook for 1 minute.",
      "Add pepper mixture and fry for 15 minutes, stirring regularly, until most liquid evaporates.",
      "Add crayfish, flaked smoked fish and 100 ml water. Simmer gently for 5 minutes, checking again for bones.",
      "Fold in spinach and cook for 4–5 minutes until hot throughout. Taste before adding salt, as smoked fish can be salty.",
    ],
    servingSuggestion:
      "Serve with rice, boiled yam or a swallow of your choice.",
    tips: [
      "Thawed frozen spinach works well; squeeze out excess water first.",
      "Leaving out iru changes the depth of flavour but keeps the recipe accessible.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · efo riro",
      url: "https://cheflolaskitchen.com/efo-riro-spinach-stew/",
    },
  }),
  r({
    id: "akara",
    name: "Akara bean fritters",
    subtitle: "Crisp bean fritters, soft and airy inside.",
    cuisine: "Nigeria",
    region,
    diet: "Plant-based",
    category: "Breakfast",
    prepTime: 30,
    cookTime: 20,
    restTime: 30,
    restLabel: "Soak beans",
    illustration: "breakfast",
    ingredients: [
      ["Dried black-eyed beans", "300 g", "Pantry"],
      ["Onions", "1 small", "Produce"],
      ["Red peppers", "½", "Produce"],
      ["Scotch bonnet", "¼, optional", "Produce"],
      ["Salt", "¾ tsp", "Pantry"],
      ["Vegetable oil", "750 ml, for deep frying", "Pantry"],
    ],
    steps: [
      "Soak beans in water for 30 minutes. Rub firmly between your palms to loosen skins; add water and pour floating skins away. Repeat until mostly peeled.",
      "Drain well. Blend beans, pepper and optional chilli with 80 ml water, adding only tiny splashes if needed, to make a thick, smooth paste.",
      "Finely dice onion. Beat the bean paste vigorously for 3–4 minutes to add air, then fold in onion and salt.",
      "Heat oil to 175°C in a deep, stable saucepan, filling it no more than halfway.",
      "Lower heaped tablespoons of batter into the oil in small batches. Turn and fry for 5–6 minutes until golden and fully set inside.",
      "Cut the first fritter open to check the centre is cooked, then drain the batch on kitchen paper. Repeat with remaining batter.",
    ],
    servingSuggestion:
      "Makes around 20 fritters; serve with bread or pap for breakfast.",
    tips: [
      "Watery batter makes flat, oily fritters; keep blending water minimal.",
      "Pre-peeled dried beans shorten preparation; follow their soaking directions.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · akara",
      url: "https://cheflolaskitchen.com/akara-acaraje/",
    },
  }),
  r({
    id: "moi-moi",
    name: "Moi moi bean puddings",
    subtitle: "Soft steamed Nigerian bean puddings with egg.",
    cuisine: "Nigeria",
    region,
    diet: "Vegetarian",
    prepTime: 30,
    cookTime: 50,
    restTime: 35,
    restLabel: "Soak & rest",
    illustration: "breakfast",
    ingredients: [
      ["Dried black-eyed beans", "300 g", "Pantry"],
      ["Red peppers", "1", "Produce"],
      ["Onions", "1", "Produce"],
      ["Fresh ginger", "10 g", "Produce"],
      ["Vegetable oil", "4 tbsp, plus a little for moulds", "Pantry"],
      ["Vegetable stock", "350 ml, cooled", "Pantry"],
      ["Eggs", "2", "Dairy & eggs"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Soak beans for 30 minutes; rub off skins and rinse repeatedly. Hard-boil eggs for 10 minutes, cool, peel and quarter.",
      "Blend peeled beans, pepper, onion and ginger with the cooled stock until completely smooth. Mix in oil and salt.",
      "Grease eight small heatproof ramekins. Divide batter between them, no more than three-quarters full, and add an egg quarter to each.",
      "Cover each loosely with foil. Stand in a steamer above simmering water, with water below the base of the ramekins.",
      "Cover the steamer and steam for 40–50 minutes, topping up boiling water as needed. A skewer inserted in the centre should emerge without wet batter.",
      "Rest for 5 minutes, then loosen around the sides and serve warm.",
    ],
    servingSuggestion:
      "Two small puddings per person with salad, rice or bread.",
    tips: [
      "The timing assumes small ramekins; large moulds need longer.",
      "For a plant-based version, omit the egg.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · moi moi",
      url: "https://cheflolaskitchen.com/make-moin-moin-moi-moi/",
    },
  }),
  r({
    id: "ewa-riro",
    name: "Ewa riro bean porridge",
    subtitle: "Soft Nigerian beans with a pepper and onion base.",
    cuisine: "Nigeria",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 90,
    ingredients: [
      ["Dried black-eyed beans", "350 g", "Pantry"],
      ["Onions", "2", "Produce"],
      ["Red peppers", "1 large", "Produce"],
      ["Red palm oil", "3 tbsp", "Pantry"],
      ["Vegetable stock", "250 ml", "Pantry"],
      ["Scotch bonnet", "½, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Sort and rinse beans. Put in a saucepan with one chopped onion and 1.2 litres water.",
      "Bring to the boil, then partially cover and simmer for 45–60 minutes, adding hot water if needed, until easily crushed.",
      "Blend pepper, remaining onion and optional chilli with a little of the stock.",
      "Heat palm oil in a separate pan, add the blend and cook on medium for 12–15 minutes, stirring until thick.",
      "Stir this sauce and remaining stock into the soft beans. Mash a few beans against the side to make a creamy texture.",
      "Simmer uncovered for 10–15 minutes, stirring often, then season. It should be spoonable, not dry.",
    ],
    servingSuggestion: "Serve with fried plantain, bread or boiled yam.",
    tips: [
      "Older beans may take longer; wait for tenderness before adding the sauce.",
      "This is a plant-based variation; many households add smoked fish or crayfish.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · ewa riro",
      url: "https://cheflolaskitchen.com/ewa-riro-stewed-beans-2/",
    },
  }),
  r({
    id: "chicken-suya",
    name: "Chicken suya skewers",
    subtitle: "A home-oven version of Nigerian peanut-spiced skewers.",
    cuisine: "Nigeria",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 20,
    restTime: 30,
    restLabel: "Marinate",
    illustration: "tray",
    ingredients: [
      ["Boneless chicken thighs", "650 g", "Meat & fish"],
      ["Roasted unsalted peanuts", "60 g", "Pantry"],
      ["Ground ginger", "1 tsp", "Pantry"],
      ["Garlic powder", "1 tsp", "Pantry"],
      ["Onion powder", "1 tsp", "Pantry"],
      ["Paprika", "2 tsp", "Pantry"],
      ["Cayenne pepper", "¼ tsp, optional", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
      ["Red onion", "1", "Produce"],
      ["Tomatoes", "2", "Produce"],
    ],
    steps: [
      "Pulse peanuts into a fine crumb, stopping before they become butter. Mix with the dry spices and salt.",
      "Cut chicken into thin, even strips. Toss with oil and most of the spice mixture; refrigerate for 30 minutes.",
      "Heat oven to 220°C conventional or 200°C fan. Soak wooden skewers in water during marinating, or use metal ones.",
      "Thread chicken loosely onto skewers and lay on an oiled rack over a baking tray.",
      "Roast for 18–22 minutes, turning halfway, until the thickest pieces reach 74°C. Avoid burning the peanut coating.",
      "Thinly slice onion and tomatoes. Serve alongside the skewers with the remaining spice mixture, kept separate from raw chicken.",
    ],
    servingSuggestion: "Add jollof, flatbread or salad for a full meal.",
    tips: [
      "Traditional yaji often uses defatted groundnut cake; these whole-peanut spices are a home adaptation.",
      "Contains peanuts; use tongs and a separate plate for cooked chicken.",
    ],
    source: {
      name: "Immaculate Bites · chicken suya",
      url: "https://www.africanbites.com/suyachicken/",
    },
  }),
  r({
    id: "asaro",
    name: "Asaro yam pottage",
    subtitle: "Yoruba-style yam simmered until creamy with pepper and spinach.",
    cuisine: "Nigeria",
    region,
    diet: "Plant-based",
    prepTime: 20,
    cookTime: 35,
    ingredients: [
      ["Puna yam", "900 g, peeled weight", "Produce"],
      ["Red peppers", "1", "Produce"],
      ["Tomatoes", "2", "Produce"],
      ["Onions", "1", "Produce"],
      ["Red palm oil", "3 tbsp", "Pantry"],
      ["Vegetable stock", "700 ml", "Pantry"],
      ["Spinach", "150 g", "Produce"],
      ["Scotch bonnet", "¼, optional", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Peel yam, cut into 3 cm cubes and rinse. Blend pepper, tomatoes, onion and optional chilli.",
      "Place yam in a heavy pot with stock. Bring to a boil, cover partly and simmer for 10 minutes.",
      "Add blended vegetables and palm oil. Stir, cover partly again and simmer for 20 minutes until yam is very tender.",
      "Stir occasionally along the base of the pot, adding hot water if it starts drying out.",
      "Mash about one-quarter of the yam into the sauce with the back of a spoon; leave the rest in chunks.",
      "Fold in chopped spinach and simmer for 3–5 minutes. Season and loosen with a splash of water if necessary.",
    ],
    servingSuggestion:
      "Serve in bowls on its own or with a side of steamed greens.",
    tips: [
      "Use African yam, not the orange sweet potatoes sometimes labelled yams.",
      "This meat-free version leaves out the dried fish or crayfish used in many family recipes.",
    ],
    source: {
      name: "Chef Lola’s Kitchen · asaro",
      url: "https://cheflolaskitchen.com/yam-porridge-pottage/",
    },
  }),
  r({
    id: "chicken-yassa",
    name: "Chicken yassa",
    subtitle: "Senegalese-style chicken with soft onions, lemon and mustard.",
    cuisine: "Senegal",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 60,
    restTime: 60,
    restLabel: "Marinate",
    ingredients: [
      ["Bone-in chicken thighs", "4 large (about 1 kg)", "Meat & fish"],
      ["Onions", "4 large", "Produce"],
      ["Lemons", "2", "Produce"],
      ["Dijon mustard", "2 tbsp", "Pantry"],
      ["Garlic", "3 cloves", "Produce"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Chicken stock", "250 ml", "Pantry"],
      ["Bay leaves", "1", "Pantry"],
      ["Black pepper", "½ tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Slice onions thinly. Mix chicken, onions, lemon juice, mustard, crushed garlic and pepper in a covered bowl; refrigerate for 1 hour.",
      "Lift chicken from the marinade. Heat oil in a heavy pan and brown the chicken for 4 minutes per side; set aside.",
      "Add onions and all marinade to the same pan. Cook for 15 minutes over medium heat, stirring until softened and starting to colour.",
      "Pour in stock, add bay leaf and return chicken. Bring the sauce to a full simmer.",
      "Cover and simmer gently for 30–35 minutes until chicken reaches 74°C at its thickest point, clear of bone.",
      "Remove bay leaf. Simmer uncovered briefly if the sauce is too thin, then taste for salt.",
    ],
    servingSuggestion: "Serve with steamed rice to soak up the onion sauce.",
    tips: [
      "Use a non-reactive bowl for the lemon marinade.",
      "The onions balance the sourness; cook them slowly rather than adding sugar.",
    ],
    source: {
      name: "Immaculate Bites · chicken yassa",
      url: "https://www.africanbites.com/yassa-chickenpoulet-au-yassa/",
    },
  }),
  r({
    id: "thieboudienne",
    name: "Thiéboudienne-inspired fish rice",
    subtitle: "A home version of Senegal’s fish, vegetable and rice dish.",
    cuisine: "Senegal",
    region,
    diet: "Meat & fish",
    prepTime: 25,
    cookTime: 70,
    illustration: "rice",
    ingredients: [
      ["Firm white fish fillets", "600 g, boneless", "Meat & fish"],
      ["Broken rice", "300 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Aubergine", "1 small", "Produce"],
      ["Cabbage", "¼ small", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Parsley", "20 g", "Produce"],
      ["Tomato paste", "3 tbsp", "Pantry"],
      ["Chopped tomatoes", "200 g", "Pantry"],
      ["Fish stock", "900 ml", "Pantry"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Limes", "1", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Chop parsley and garlic finely; rub onto fish. Cut carrots, aubergine and cabbage into large pieces. Rinse rice.",
      "Heat oil in a wide pot. Cook diced onion for 5 minutes; stir in tomato paste for 2 minutes, then tomatoes and stock.",
      "Add vegetables and simmer for 20–25 minutes, lifting them out as they become tender.",
      "Lower fish into the broth and poach gently for 8–12 minutes until it reaches 63°C. Lift onto a covered plate with vegetables.",
      "Measure 600 ml broth back into the pot, topping up with water if needed. Add rice, bring to a simmer, cover and cook on low for 20–25 minutes.",
      "Check rice is tender, adding a splash more broth if needed. Return fish and vegetables for the final 5 minutes to heat through; serve with lime.",
    ],
    servingSuggestion:
      "Arrange the rice on a platter with vegetables and fish on top.",
    tips: [
      "This simplified version omits fermented fish and nététou; it is not a full traditional preparation.",
      "Broken rice varies; follow its liquid needs and check for tenderness.",
    ],
    source: {
      name: "196 flavors · thiéboudienne",
      url: "https://www.196flavors.com/senegal-thieboudienne/",
    },
  }),
  r({
    id: "ndambe",
    name: "Ndambe bean baguettes",
    subtitle: "A meat-free take on Senegal’s warm bean sandwich.",
    cuisine: "Senegal",
    region,
    diet: "Plant-based",
    prepTime: 10,
    cookTime: 25,
    illustration: "tray",
    ingredients: [
      ["Black-eyed beans", "2 × 400 g cans", "Pantry"],
      ["Baguettes", "2 medium", "Bakery"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Vegetable stock", "250 ml", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Chilli powder", "¼ tsp, optional", "Pantry"],
      ["White wine vinegar", "1 tsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Drain and rinse beans. Dice onion and mince garlic. Cut baguettes into four portions and split without cutting all the way through.",
      "Heat oil in a saucepan and cook onion over medium heat for 6 minutes until soft.",
      "Stir in garlic, tomato paste and optional chilli. Cook for 2 minutes, scraping the bottom as you stir.",
      "Add beans and stock. Simmer uncovered for 12–15 minutes, mashing a few beans so the filling holds together.",
      "Add vinegar and black pepper; taste for salt. Cook a little longer if the filling is still runny.",
      "Warm bread briefly if desired and spoon in the hot beans just before serving.",
    ],
    servingSuggestion: "Serve with tomato and cucumber on the side.",
    tips: [
      "This version uses canned beans and leaves out beef for a quicker lunch.",
      "Keep bread and filling separate until serving to avoid soggy sandwiches.",
    ],
    source: {
      name: "International Cuisine · ndambe",
      url: "https://www.internationalcuisine.com/ndambe/",
    },
  }),
  r({
    id: "beef-maafe",
    name: "Beef maafé",
    subtitle: "A slow peanut and tomato stew enjoyed in Mali and Senegal.",
    cuisine: "Mali & Senegal",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 125,
    ingredients: [
      ["Stewing beef", "650 g", "Meat & fish"],
      ["Unsweetened peanut butter", "150 g", "Pantry"],
      ["Carrots", "3", "Produce"],
      ["Sweet potatoes", "400 g", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Chopped tomatoes", "400 g can", "Pantry"],
      ["Beef stock", "750 ml", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Cut beef into 3 cm cubes and pat dry. Peel carrots and sweet potatoes; cut into substantial chunks. Dice onion and garlic.",
      "Heat oil in a heavy casserole. Brown beef in batches, about 8 minutes total, and set aside.",
      "Soften onion for 5 minutes. Stir in garlic and tomato paste for 2 minutes, then add tomatoes, stock and beef.",
      "Bring to a simmer, cover and cook gently for 65–75 minutes, until beef is starting to soften.",
      "Whisk peanut butter with a ladle of hot broth, return to the pot and add the vegetables. Simmer for 25–30 minutes, stirring along the bottom.",
      "Check beef and vegetables are tender; cook longer if needed. Add water if too thick and taste for salt.",
    ],
    servingSuggestion: "Serve with plain rice or millet, prepared separately.",
    tips: [
      "Cooking time depends on the beef cut; tenderness matters more than the clock.",
      "Unsweetened peanut butter gives a savoury sauce without added sugar.",
    ],
    source: {
      name: "196 flavors · maafé",
      url: "https://www.196flavors.com/mafe/",
    },
  }),
  r({
    id: "domoda",
    name: "Vegetable domoda",
    subtitle: "A Gambian-inspired peanut stew with sweet potato.",
    cuisine: "The Gambia",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 35,
    ingredients: [
      ["Sweet potatoes", "600 g", "Produce"],
      ["Chopped tomatoes", "400 g can", "Pantry"],
      ["Unsweetened peanut butter", "150 g", "Pantry"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Fresh ginger", "20 g", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Vegetable stock", "750 ml", "Pantry"],
      ["Spinach", "150 g", "Produce"],
      ["Limes", "1", "Produce"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Chilli flakes", "¼ tsp, optional", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Peel sweet potatoes and cut into 2 cm cubes. Dice onion, crush garlic and grate ginger.",
      "Warm oil in a large pot. Cook onion for 5 minutes, then add garlic, ginger, tomato paste and optional chilli for 2 minutes.",
      "Add tomatoes, stock and sweet potato. Bring to a simmer, cover loosely and cook for 15 minutes.",
      "Whisk peanut butter with a ladle of warm broth until smooth, then stir into the pot.",
      "Simmer gently for 10 more minutes, stirring regularly, until sweet potato is tender and the sauce is creamy.",
      "Fold in spinach for 2 minutes. Add lime juice and salt to taste, loosening with water if necessary.",
    ],
    servingSuggestion: "Spoon over rice or serve with steamed millet.",
    tips: [
      "This vegetable adaptation uses sweet potato; domoda also comes in meat and fish versions.",
      "Stir the base frequently after adding peanuts to prevent scorching.",
    ],
    source: {
      name: "Rainbow Plant Life · vegetable domoda",
      url: "https://rainbowplantlife.com/vegan-west-african-peanut-stew/",
    },
  }),
  r({
    id: "vegetable-benachin",
    name: "Vegetable benachin",
    subtitle: "Gambian-style one-pot rice with large pieces of vegetables.",
    cuisine: "The Gambia",
    region,
    diet: "Plant-based",
    prepTime: 20,
    cookTime: 55,
    illustration: "rice",
    ingredients: [
      ["Long-grain rice", "300 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Cabbage", "¼ small", "Produce"],
      ["Aubergine", "1 small", "Produce"],
      ["Onions", "1", "Produce"],
      ["Tomatoes", "3", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Garlic", "2 cloves", "Produce"],
      ["Vegetable stock", "800 ml", "Pantry"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Bay leaves", "1", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Rinse rice. Cut carrots and aubergine into large chunks and cabbage into wedges. Dice onions and tomatoes; mince garlic.",
      "Heat oil in a heavy pot. Fry onion for 5 minutes, then garlic and tomato paste for 2 minutes.",
      "Add tomatoes, stock and bay leaf. Bring to a simmer, add vegetables and cook for 15–20 minutes until just tender.",
      "Lift vegetables onto a plate. Measure 600 ml of the sauce back into the pot, topping up with water if needed, and taste for salt.",
      "Add rice, bring to a simmer, cover tightly and cook over low heat for 20–25 minutes. Add a small splash of water if grains remain firm.",
      "Place vegetables on top for the final 5 minutes to heat through. Remove bay leaf and serve.",
    ],
    servingSuggestion:
      "Serve as a vegetable rice meal; add cooked beans for a more filling plate.",
    tips: [
      "This is a vegetable adaptation of benachin, which often includes fish or meat.",
      "Keeping the vegetables large stops them disappearing into the rice.",
    ],
    source: {
      name: "Access Gambia · benachin",
      url: "https://accessgambia.com/information/jollof-rice-benachin.html",
    },
  }),
  r({
    id: "kedjenou",
    name: "Kedjenou chicken",
    subtitle: "Ivorian chicken slowly cooked with aubergine and tomato.",
    cuisine: "Côte d’Ivoire",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 60,
    ingredients: [
      ["Bone-in chicken thighs", "4 large (about 1 kg)", "Meat & fish"],
      ["Aubergine", "1 large", "Produce"],
      ["Tomatoes", "4", "Produce"],
      ["Onions", "2", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Fresh ginger", "20 g", "Produce"],
      ["Dried thyme", "1 tsp", "Pantry"],
      ["Bay leaves", "1", "Pantry"],
      ["Scotch bonnet", "1, optional", "Produce"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Salt", "½ tsp, or to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 170°C conventional or 150°C fan. Cut aubergine into 3 cm pieces, chop tomatoes and slice onions.",
      "Oil an ovenproof casserole with a snug lid. Add vegetables, grated ginger, crushed garlic, thyme, bay and salt.",
      "Nestle chicken among vegetables and add the optional whole chilli. Pour in 50 ml water to help the initial steam form.",
      "Cover tightly and bake for 50–60 minutes. Using oven gloves, gently swirl the pot halfway through; avoid lifting the lid repeatedly.",
      "Check chicken reaches 74°C away from the bone and vegetables are soft. Return covered to the oven if needed.",
      "Remove bay leaf and chilli. Stir the sauce carefully and season before serving.",
    ],
    servingSuggestion: "Serve with attiéké or plain rice.",
    tips: [
      "This oven method adapts traditional sealed-pot cooking for a home kitchen.",
      "A heavy casserole with a tight lid keeps the vegetables’ moisture inside.",
    ],
    source: {
      name: "Immaculate Bites · kedjenou",
      url: "https://www.africanbites.com/kedjenou-chicken/",
    },
  }),
  r({
    id: "attieke-fish",
    name: "Attiéké with baked fish",
    subtitle: "Ivorian cassava couscous with fish and tomato salad.",
    cuisine: "Côte d’Ivoire",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 25,
    illustration: "tray",
    ingredients: [
      ["Dried attiéké", "300 g", "Pantry"],
      ["White fish fillets", "4 × 150 g", "Meat & fish"],
      ["Tomatoes", "3", "Produce"],
      ["Red onion", "1 small", "Produce"],
      ["Cucumber", "½", "Produce"],
      ["Limes", "2", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Paprika", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 200°C conventional or 180°C fan. Place fish in a baking dish and check carefully for bones.",
      "Mix 1 tablespoon oil with crushed garlic, paprika and juice of one lime. Rub over fish and season lightly.",
      "Bake for 15–20 minutes, depending on thickness, until fish reaches 63°C in the centre.",
      "Meanwhile hydrate and steam the dried attiéké following its packet instructions. Break up clumps with a fork until light and hot throughout.",
      "Dice tomatoes, onion and cucumber finely. Toss with remaining oil and lime juice, and salt to taste.",
      "Divide attiéké between plates, top with salad and add the fish alongside.",
    ],
    servingSuggestion:
      "A full meal; offer a chilli sauce separately if desired.",
    tips: [
      "Use commercially prepared attiéké; this recipe does not process raw cassava.",
      "Frozen and dried attiéké have different instructions, so check the packet.",
    ],
    source: {
      name: "196 flavors · attiéké",
      url: "https://www.196flavors.com/ivory-coast-attieke/",
    },
  }),
  r({
    id: "fonio-pilaf",
    name: "Fonio vegetable pilaf",
    subtitle:
      "A quick, fluffy grain bowl inspired by West African fonio dishes.",
    cuisine: "West African-inspired",
    region,
    diet: "Plant-based",
    prepTime: 10,
    cookTime: 20,
    illustration: "rice",
    ingredients: [
      ["Quick-cooking fonio", "250 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Onions", "1 small", "Produce"],
      ["Spinach", "120 g", "Produce"],
      ["Cooked chickpeas", "400 g can", "Pantry"],
      ["Vegetable stock", "500 ml; check fonio packet", "Pantry"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Parsley", "15 g", "Produce"],
      ["Lemons", "1", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Finely dice onion and carrots. Rinse and drain chickpeas. Check your fonio packet for rinsing and liquid requirements.",
      "Heat oil in a saucepan. Cook onion and carrots for 7–8 minutes until tender, stirring regularly.",
      "Stir in fonio and chickpeas. Add the quantity of hot stock specified by the fonio packet and bring to a simmer.",
      "Cover and cook for the packet time, usually only a few minutes for quick-cooking fonio. Turn off the heat once liquid is absorbed.",
      "Place spinach on top, cover again and stand for 5 minutes so it wilts while the grains finish steaming.",
      "Fluff with a fork, mix through chopped parsley and lemon juice, then taste for salt.",
    ],
    servingSuggestion:
      "Serve warm as a grain bowl or alongside grilled vegetables.",
    tips: [
      "This is a modern vegetable pilaf rather than a dish claimed for one country.",
      "If using couscous or quinoa instead, follow that grain’s cooking time and water ratio.",
    ],
    source: {
      name: "Yolélé · fonio cooking inspiration",
      url: "https://yolele.com/blogs/recipes/fonio-pilaf-with-dates-carrots-and-peanuts",
    },
  }),
  r({
    id: "plasas",
    name: "Plasas greens & beef",
    subtitle: "A Gambian-style spinach stew with smoked fish and peanuts.",
    cuisine: "The Gambia",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 110,
    illustration: "greens",
    ingredients: [
      ["Stewing beef", "400 g", "Meat & fish"],
      ["Frozen chopped spinach", "500 g", "Produce"],
      ["Smoked mackerel", "150 g, skin and bones removed", "Meat & fish"],
      ["Onions", "1", "Produce"],
      ["Unsweetened peanut butter", "60 g", "Pantry"],
      ["Red palm oil", "3 tbsp", "Pantry"],
      ["Beef stock", "750 ml", "Pantry"],
      ["Chilli flakes", "¼ tsp, optional", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Cut beef into 2 cm cubes. Dice onion. Thaw spinach and squeeze out excess liquid; flake fish and remove any bones.",
      "Put beef, onion, stock and optional chilli into a heavy saucepan. Bring to the boil, then reduce to a simmer.",
      "Stir in palm oil, cover partly and cook gently for 75–90 minutes until beef is tender, adding water if needed.",
      "Whisk peanut butter with a ladle of hot cooking liquid until smooth and return to the pot.",
      "Add spinach and smoked fish. Simmer for 10–15 minutes, stirring regularly, until everything is piping hot and the sauce thickens.",
      "Taste before adding salt. Add a splash of water if the stew is too thick to spoon easily.",
    ],
    servingSuggestion: "Serve over plain rice.",
    tips: [
      "This version uses spinach, which is easy to find, rather than cassava leaves.",
      "Check smoked fish thoroughly for small bones before adding it.",
    ],
    source: {
      name: "Access Gambia · plasas",
      url: "https://www.accessgambia.com/information/plasas-dish.html",
    },
  }),
];
