import { defineRecipe as r } from "./recipe-helpers";
const region = "Everyday" as const;
export const everydayRecipes = [
  r({
    id: "lentil-bolognese",
    name: "Lentil bolognese",
    subtitle: "A rich vegetable sauce for a comforting pasta night.",
    cuisine: "Italian-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Spaghetti", "350 g", "Pantry"],
      ["Cooked green lentils", "2 × 400 g cans", "Pantry"],
      ["Chopped tomatoes", "800 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Finely dice onion and carrots, mince garlic and drain lentils.",
      "Heat oil in a deep pan. Cook onion and carrot over medium heat for 8 minutes until softened.",
      "Stir in garlic, tomato paste and oregano for 1 minute. Add tomatoes, lentils and 150 ml water.",
      "Simmer uncovered for 20 minutes, stirring occasionally. Mash a few lentils to thicken the sauce and season.",
      "Meanwhile boil spaghetti in salted water according to its packet. Reserve a mug of cooking water, then drain.",
      "Toss pasta with the sauce, adding a splash of reserved water until it coats the strands.",
    ],
    servingSuggestion: "Serve with salad and optional grated cheese.",
    tips: [
      "Canned lentils are already cooked; dried lentils need separate cooking first.",
      "Finely chopped mushrooms can replace one carrot for a deeper flavour.",
    ],
  }),
  r({
    id: "chicken-traybake",
    name: "Lemon chicken traybake",
    subtitle: "Chicken, potatoes and carrots in one roasting tray.",
    cuisine: "Everyday favourites",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 50,
    ingredients: [
      ["Bone-in chicken thighs", "4 large", "Meat & fish"],
      ["Potatoes", "700 g", "Produce"],
      ["Carrots", "400 g", "Produce"],
      ["Red onion", "1", "Produce"],
      ["Lemons", "1", "Produce"],
      ["Garlic", "4 cloves", "Produce"],
      ["Olive oil", "3 tbsp", "Pantry"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Heat oven to 210°C conventional or 190°C fan. Cut potatoes into 3 cm chunks, carrots into thick batons and onion into wedges.",
      "Spread vegetables in a large roasting tray. Toss with 2 tablespoons oil, half the oregano, salt and pepper.",
      "Rub chicken with remaining oil and oregano. Nestle skin-side up among the vegetables, leaving space around each piece.",
      "Add crushed garlic cloves and lemon wedges. Roast for 40 minutes, turning the vegetables halfway through.",
      "Check the chicken reaches 74°C away from the bone and potatoes are tender. Cook for another 5–10 minutes if necessary.",
      "Rest for 5 minutes, squeeze the roasted lemon over the tray and spoon the juices onto each serving.",
    ],
    servingSuggestion: "Add steamed broccoli or a green salad.",
    tips: [
      "Use two trays if the vegetables are crowded.",
      "Boneless thighs cook faster; add them after the vegetables have roasted for 15 minutes.",
    ],
  }),
  r({
    id: "vegetable-couscous",
    name: "Roasted vegetable couscous",
    subtitle: "Fluffy grains, colourful vegetables and chickpeas.",
    cuisine: "North African-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 25,
    ingredients: [
      ["Couscous", "250 g", "Pantry"],
      ["Cooked chickpeas", "400 g can", "Pantry"],
      ["Courgettes", "2", "Produce"],
      ["Red peppers", "2", "Produce"],
      ["Red onion", "1", "Produce"],
      ["Vegetable stock", "300 ml, or packet quantity", "Pantry"],
      ["Olive oil", "3 tbsp", "Pantry"],
      ["Ground cumin", "1 tsp", "Pantry"],
      ["Lemons", "1", "Produce"],
      ["Parsley", "15 g", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 220°C conventional or 200°C fan. Chop courgettes, peppers and onion into bite-size pieces.",
      "Drain chickpeas. Toss them and the vegetables with 2 tablespoons oil and cumin on a large tray.",
      "Roast for 20–25 minutes, turning once, until vegetables are tender and browned at the edges.",
      "Put couscous in a heatproof bowl. Pour over boiling stock using the packet ratio, cover and stand for 5 minutes.",
      "Fluff grains thoroughly with a fork, then fold in roasted vegetables and chickpeas.",
      "Add remaining oil, chopped parsley, lemon juice and salt to taste. Mix gently and serve warm.",
    ],
    servingSuggestion:
      "Serve as a grain bowl, with yoghurt on the side if desired.",
    tips: [
      "Couscous contains wheat.",
      "Keep vegetables in one layer so they roast instead of steaming.",
    ],
  }),
  r({
    id: "overnight-oats",
    name: "Berry overnight oats",
    subtitle: "Breakfast ready when the family wakes up.",
    cuisine: "Everyday favourites",
    region,
    diet: "Vegetarian",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 0,
    restTime: 480,
    restLabel: "Chill",
    ingredients: [
      ["Rolled oats", "200 g", "Pantry"],
      ["Milk", "400 ml", "Dairy & eggs"],
      ["Plain yoghurt", "200 g", "Dairy & eggs"],
      ["Chia seeds", "2 tbsp", "Pantry"],
      ["Fresh berries", "250 g", "Produce"],
      ["Maple syrup", "2 tbsp, optional", "Pantry"],
    ],
    steps: [
      "Set out four clean jars or covered breakfast bowls. Rinse and dry fresh berries.",
      "Mix oats and chia seeds in a large bowl, breaking up any clumps.",
      "Stir in milk, yoghurt and optional maple syrup until evenly combined.",
      "Divide between the jars, cover and refrigerate for at least 8 hours.",
      "In the morning, stir each portion. Add a splash of milk if it is thicker than you like.",
      "Top with fresh berries immediately before eating and keep any uneaten portions refrigerated.",
    ],
    servingSuggestion:
      "Serve cold, or warm the oat mixture separately before adding yoghurt and fruit.",
    tips: [
      "Use rolled oats, not steel-cut oats, for this timing.",
      "Plant milk and dairy-free yoghurt make a plant-based version.",
    ],
  }),
  r({
    id: "shakshuka",
    name: "Tomato & pepper shakshuka",
    subtitle: "Eggs gently cooked in a cumin-scented tomato sauce.",
    cuisine: "North African-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 10,
    cookTime: 30,
    ingredients: [
      ["Eggs", "8", "Dairy & eggs"],
      ["Chopped tomatoes", "800 g", "Pantry"],
      ["Red peppers", "2", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Ground cumin", "1 tsp", "Pantry"],
      ["Paprika", "1 tsp", "Pantry"],
      ["Parsley", "15 g", "Produce"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Dice onion and peppers and mince garlic. Choose a wide frying pan with a lid.",
      "Heat oil over medium heat. Soften onion and peppers for 8–10 minutes.",
      "Add garlic, cumin and paprika and stir for 1 minute. Pour in tomatoes and simmer for 10–12 minutes until thick.",
      "Taste the sauce for salt, then make eight small hollows with a spoon.",
      "Crack an egg into each hollow. Cover and cook on low for 8–10 minutes, or until both whites and yolks are set.",
      "Scatter chopped parsley on top and serve straight from the pan.",
    ],
    servingSuggestion:
      "Serve with bread or warm flatbreads, added separately to your shopping list.",
    tips: [
      "A thick sauce helps the eggs stay in their hollows.",
      "Use two pans if eight eggs do not fit comfortably.",
    ],
  }),
  r({
    id: "egg-fried-rice",
    name: "Vegetable egg fried rice",
    subtitle: "A quick rice supper with peas, carrots and soft egg.",
    cuisine: "Chinese-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      ["Ready-cooked rice", "600 g (sealed ready-to-heat packs)", "Pantry"],
      ["Eggs", "4", "Dairy & eggs"],
      ["Frozen peas", "200 g", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Spring onions", "4", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Soy sauce", "2 tbsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Sesame oil", "1 tsp", "Pantry"],
    ],
    steps: [
      "Dice carrots finely, slice spring onions and mince garlic. Beat eggs in a small bowl and break up clumps in the packaged rice.",
      "Heat half the vegetable oil in a wide pan. Scramble eggs until set, then transfer to a clean plate.",
      "Add remaining vegetable oil and cook carrots for 4 minutes. Add garlic and peas for 2 minutes.",
      "Add rice and soy sauce. Stir-fry for 4–5 minutes, breaking up clumps, until steaming hot throughout.",
      "Return egg to the pan and add spring onions. Toss for another minute.",
      "Finish with sesame oil. Taste before adding any more soy sauce and serve immediately.",
    ],
    servingSuggestion: "Serve with sliced cucumber or steamed greens.",
    tips: [
      "Ready-cooked packs keep this recipe within 25 minutes.",
      "If using leftover rice, use only rice that was promptly cooled and refrigerated; heat thoroughly.",
    ],
  }),
  r({
    id: "chicken-stir-fry",
    name: "Ginger chicken stir-fry",
    subtitle: "Chicken and crisp vegetables in a light savoury sauce.",
    cuisine: "Chinese-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 15,
    ingredients: [
      ["Chicken breast", "600 g", "Meat & fish"],
      ["Broccoli", "1 small head", "Produce"],
      ["Red peppers", "1", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Fresh ginger", "20 g", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Soy sauce", "3 tbsp", "Pantry"],
      ["Cornflour", "2 tsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Rice", "300 g", "Pantry"],
    ],
    steps: [
      "Start cooking rice according to its packet. Thinly slice chicken; cut vegetables into small, even pieces.",
      "Mix soy sauce, cornflour and 150 ml cold water. Grate ginger and mince garlic.",
      "Heat half the oil in a large pan. Stir-fry chicken in batches for 5–6 minutes, then transfer to a clean bowl.",
      "Add remaining oil and vegetables. Stir-fry for 4 minutes; add ginger and garlic for 1 minute.",
      "Return chicken and stir in the sauce. Bubble for 2–3 minutes until glossy and the chicken reaches 74°C.",
      "Loosen with a splash of water if needed and serve immediately over rice.",
    ],
    servingSuggestion:
      "Offer extra soy sauce at the table rather than salting heavily.",
    tips: [
      "Prepare everything before heating the pan; cooking moves quickly.",
      "Cut broccoli small so it cooks at the same speed as the other vegetables.",
    ],
  }),
  r({
    id: "crispy-tofu-bowls",
    name: "Crispy tofu rice bowls",
    subtitle: "Golden tofu with broccoli and a tangy soy glaze.",
    cuisine: "East Asian-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 25,
    ingredients: [
      ["Firm tofu", "600 g", "Pantry"],
      ["Rice", "300 g", "Pantry"],
      ["Broccoli", "1 large head", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Soy sauce", "3 tbsp", "Pantry"],
      ["Rice vinegar", "1 tbsp", "Pantry"],
      ["Maple syrup", "1 tbsp", "Pantry"],
      ["Cornflour", "2 tbsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Garlic", "2 cloves", "Produce"],
    ],
    steps: [
      "Pat tofu dry thoroughly and cut into 2 cm cubes. Start rice cooking according to its packet.",
      "Toss tofu with cornflour. Heat oil in a non-stick pan and fry for 10–12 minutes, turning until several sides are golden.",
      "Meanwhile cut broccoli into florets and carrots into thin batons. Steam for 5–7 minutes until just tender.",
      "Mix soy sauce, vinegar, maple syrup, crushed garlic and 80 ml water in a bowl.",
      "Pour sauce around the tofu and bubble for 2–3 minutes, tossing gently until coated.",
      "Divide rice between bowls, add vegetables and tofu, then spoon over the remaining glaze.",
    ],
    servingSuggestion: "Add sliced spring onions or sesame seeds if available.",
    tips: [
      "Firm tofu holds its shape; silken tofu is too delicate here.",
      "A dry surface helps the coating turn crisp.",
    ],
  }),
  r({
    id: "minestrone",
    name: "Vegetable minestrone",
    subtitle: "A tomato broth full of beans, vegetables and small pasta.",
    cuisine: "Italian-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Small pasta shapes", "150 g", "Pantry"],
      ["Cannellini beans", "400 g can", "Pantry"],
      ["Chopped tomatoes", "400 g can", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Celery", "2 stalks", "Produce"],
      ["Courgettes", "1", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Vegetable stock", "1.2 litres", "Pantry"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Dice onion, carrots, celery and courgette into small pieces. Mince garlic and drain beans.",
      "Heat oil in a soup pot. Soften onion, carrots and celery for 8 minutes.",
      "Add garlic and oregano for 1 minute, then tomatoes, stock and courgette.",
      "Bring to a simmer and cook for 10 minutes, until vegetables are nearly tender.",
      "Add pasta and beans. Simmer for the pasta packet time, stirring occasionally so it does not stick.",
      "Check pasta is tender, add water if the soup is too thick and season to taste.",
    ],
    servingSuggestion: "Serve in deep bowls with crusty bread.",
    tips: [
      "For make-ahead soup, cook pasta separately and add it to each serving.",
      "Swap courgette for chopped green beans if preferred.",
    ],
  }),
  r({
    id: "tomato-bean-soup",
    name: "Tomato & white bean soup",
    subtitle: "Creamy without cream, thanks to blended white beans.",
    cuisine: "Everyday favourites",
    region,
    diet: "Plant-based",
    prepTime: 10,
    cookTime: 25,
    ingredients: [
      ["Chopped tomatoes", "800 g", "Pantry"],
      ["Cannellini beans", "400 g can", "Pantry"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Carrots", "1", "Produce"],
      ["Vegetable stock", "600 ml", "Pantry"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Dried basil", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Dice onion and carrot, mince garlic and rinse the beans.",
      "Warm oil in a saucepan. Cook onion and carrot for 7 minutes until softened.",
      "Add garlic and basil and stir for 1 minute, then pour in tomatoes and stock.",
      "Add beans, bring to a gentle simmer and cook for 15 minutes until the carrot is tender.",
      "Remove from the heat. Use a stick blender to blend carefully until smooth, keeping the blade submerged.",
      "Return to low heat, loosen with water if needed and season with salt and pepper.",
    ],
    servingSuggestion: "Serve with toast or a cheese sandwich.",
    tips: [
      "If using a jug blender, cool the soup first and follow its hot-liquid instructions.",
      "Leave half the beans whole for more texture.",
    ],
  }),
  r({
    id: "three-bean-chilli",
    name: "Three-bean chilli",
    subtitle: "A mild, smoky pot of beans and vegetables.",
    cuisine: "Tex-Mex-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Black beans", "400 g can", "Pantry"],
      ["Kidney beans", "400 g can", "Pantry"],
      ["Cannellini beans", "400 g can", "Pantry"],
      ["Chopped tomatoes", "800 g", "Pantry"],
      ["Red peppers", "2", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Ground cumin", "2 tsp", "Pantry"],
      ["Smoked paprika", "2 tsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Drain and rinse all beans. Chop peppers and onion and mince garlic.",
      "Heat oil in a wide saucepan. Soften onion and peppers over medium heat for 8 minutes.",
      "Add garlic, cumin and paprika and stir for 1 minute.",
      "Pour in tomatoes and 200 ml water. Add beans and bring to a gentle simmer.",
      "Cook uncovered for 20 minutes, stirring now and then. Mash a few beans to thicken the sauce if desired.",
      "Taste and season. Add a splash of water if too thick, or simmer longer if watery.",
    ],
    servingSuggestion: "Serve with rice, baked potatoes or tortillas.",
    tips: [
      "Use canned kidney beans, which are already safely cooked.",
      "Keep chilli heat separate so everyone can choose their own.",
    ],
  }),
  r({
    id: "beef-chilli",
    name: "Beef & bean chilli",
    subtitle: "A filling family pot with cumin and a gentle smoky finish.",
    cuisine: "Tex-Mex-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 40,
    ingredients: [
      ["Beef mince", "500 g", "Meat & fish"],
      ["Kidney beans", "400 g can", "Pantry"],
      ["Chopped tomatoes", "800 g", "Pantry"],
      ["Onions", "1", "Produce"],
      ["Red peppers", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Ground cumin", "2 tsp", "Pantry"],
      ["Smoked paprika", "2 tsp", "Pantry"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Dice onion and pepper, mince garlic and rinse canned beans.",
      "Heat oil in a casserole and brown mince for 6–8 minutes, breaking it into small pieces.",
      "Add onion and pepper and cook for 5 minutes. Stir in garlic, tomato paste, cumin and paprika for 1 minute.",
      "Add tomatoes, beans and 200 ml water. Bring to a simmer and partly cover.",
      "Cook gently for 25–30 minutes, stirring occasionally, until the sauce thickens and the mince is cooked through to 71°C.",
      "Taste for salt and adjust thickness with a little water before serving.",
    ],
    servingSuggestion: "Serve with rice and optional yoghurt or grated cheese.",
    tips: [
      "Browning the mince builds flavour; avoid adding tomatoes too early.",
      "Turkey mince also works, but must reach 74°C.",
    ],
  }),
  r({
    id: "salmon-fishcakes",
    name: "Salmon & potato fishcakes",
    subtitle: "Golden fishcakes made with pantry salmon and fresh potato.",
    cuisine: "Everyday favourites",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 30,
    restTime: 15,
    restLabel: "Chill",
    ingredients: [
      ["Potatoes", "600 g", "Produce"],
      ["Canned salmon", "2 × 170 g cans", "Meat & fish"],
      ["Eggs", "1", "Dairy & eggs"],
      ["Breadcrumbs", "80 g", "Pantry"],
      ["Spring onions", "3", "Produce"],
      ["Lemons", "1", "Produce"],
      ["Plain flour", "2 tbsp", "Pantry"],
      ["Vegetable oil", "3 tbsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Peel and cube potatoes. Boil for 15 minutes until tender, drain well and let steam escape before mashing without milk.",
      "Drain salmon, check for bones and flake it. Finely slice spring onions and zest the lemon.",
      "Mix potato, salmon, spring onions, zest, pepper and beaten egg. Shape into eight flat cakes and chill for 15 minutes.",
      "Dust cakes lightly with flour, then press into breadcrumbs on both sides.",
      "Heat oil in a non-stick pan. Fry in batches over medium heat for 4–5 minutes per side until golden and hot through to 74°C.",
      "Drain on kitchen paper and serve with lemon wedges.",
    ],
    servingSuggestion: "Serve two cakes per person with peas or salad.",
    tips: [
      "Dry mash holds together better than wet mash.",
      "Turn gently with a wide spatula after the first side has formed a crust.",
    ],
  }),
  r({
    id: "tuna-pasta-bake",
    name: "Tuna & sweetcorn pasta bake",
    subtitle: "A bubbling tomato pasta bake with a cheesy top.",
    cuisine: "Everyday favourites",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Penne pasta", "350 g", "Pantry"],
      ["Canned tuna", "2 × 160 g cans", "Meat & fish"],
      ["Sweetcorn", "200 g", "Produce"],
      ["Passata", "600 ml", "Pantry"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Cheddar cheese", "120 g", "Dairy & eggs"],
      ["Olive oil", "1 tbsp", "Pantry"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 200°C conventional or 180°C fan. Boil pasta for 2 minutes less than its packet time and drain, reserving some water.",
      "Dice onion and garlic. Soften onion in oil for 5 minutes, then stir in garlic and oregano.",
      "Add passata and 100 ml pasta water. Simmer for 5 minutes and season.",
      "Drain tuna and fold into the sauce with sweetcorn and pasta. Spoon into an ovenproof dish.",
      "Grate cheese over the top and bake for 20–25 minutes until bubbling and hot through to 74°C.",
      "Stand for 5 minutes before dividing into portions.",
    ],
    servingSuggestion: "Serve with steamed broccoli or a crunchy salad.",
    tips: [
      "Slightly undercooked pasta finishes cooking in the sauce.",
      "Add more reserved pasta water if the mixture looks dry before baking.",
    ],
  }),
  r({
    id: "chicken-noodle-soup",
    name: "Chicken noodle soup",
    subtitle: "A warm broth with shredded chicken, noodles and vegetables.",
    cuisine: "Everyday favourites",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Chicken breast", "500 g", "Meat & fish"],
      ["Egg noodles", "200 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Celery", "2 stalks", "Produce"],
      ["Onions", "1", "Produce"],
      ["Chicken stock", "1.5 litres", "Pantry"],
      ["Garlic", "2 cloves", "Produce"],
      ["Olive oil", "1 tbsp", "Pantry"],
      ["Parsley", "15 g", "Produce"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Dice onion, celery and carrots; mince garlic. Heat oil in a large soup pot.",
      "Cook the vegetables for 7 minutes, stirring, then add garlic for 1 minute.",
      "Pour in stock and add whole chicken breasts. Bring to a gentle simmer and cook for 15–20 minutes until chicken reaches 74°C.",
      "Lift chicken onto a clean board. Add noodles to the broth and cook according to their packet time.",
      "Shred chicken with two forks and return it to the pot for the final minute.",
      "Stir in chopped parsley and pepper. Taste the broth before adding any extra seasoning.",
    ],
    servingSuggestion: "Serve in large bowls with bread if desired.",
    tips: [
      "A gentle simmer keeps chicken tender.",
      "Cook noodles separately if making soup ahead, so they do not absorb all the broth.",
    ],
  }),
  r({
    id: "mushroom-risotto",
    name: "Mushroom risotto",
    subtitle: "Creamy rice with browned mushrooms and parmesan-style cheese.",
    cuisine: "Italian-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 15,
    cookTime: 35,
    ingredients: [
      ["Arborio rice", "300 g", "Pantry"],
      ["Mushrooms", "400 g", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Vegetable stock", "1.2 litres", "Pantry"],
      ["Vegetarian hard cheese", "60 g", "Dairy & eggs"],
      ["Butter", "25 g", "Dairy & eggs"],
      ["Olive oil", "1 tbsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Slice mushrooms, dice onion and mince garlic. Keep stock hot in a small saucepan.",
      "Heat oil and half the butter in a wide pan. Brown mushrooms for 6–8 minutes and set aside.",
      "Soften onion in the same pan for 5 minutes, adding garlic for the final minute. Stir in dry rice for 1 minute.",
      "Add a ladle of hot stock and stir until mostly absorbed. Continue adding stock a ladle at a time for 20–25 minutes, stirring often.",
      "When rice is tender with a slight bite, fold in mushrooms, grated cheese, remaining butter and pepper.",
      "Add enough stock to make the risotto flow gently when spooned. Rest for 2 minutes and serve immediately.",
    ],
    servingSuggestion: "Serve with a green salad or steamed peas.",
    tips: [
      "Choose cheese labelled vegetarian if needed.",
      "Do not rinse risotto rice; its starch makes the sauce creamy.",
    ],
  }),
  r({
    id: "spinach-frittata",
    name: "Spinach & potato frittata",
    subtitle: "A simple baked egg meal with tender potato and feta.",
    cuisine: "Mediterranean-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      ["Eggs", "8", "Dairy & eggs"],
      ["Potatoes", "400 g", "Produce"],
      ["Spinach", "150 g", "Produce"],
      ["Feta", "100 g", "Dairy & eggs"],
      ["Milk", "80 ml", "Dairy & eggs"],
      ["Onions", "1", "Produce"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Heat oven to 190°C conventional or 170°C fan. Slice potatoes thinly and boil for 6–8 minutes until just tender; drain.",
      "Dice onion and cook in oil in an ovenproof frying pan for 5 minutes.",
      "Add spinach and stir until wilted. Spread potatoes evenly through the pan.",
      "Whisk eggs, milk and pepper. Pour over vegetables and scatter crumbled feta on top.",
      "Cook on low for 2 minutes, then transfer to the oven for 15–20 minutes until set in the centre, reaching 71°C.",
      "Rest for 5 minutes, loosen the edges with a spatula and cut into wedges.",
    ],
    servingSuggestion: "Serve with tomatoes or a green salad.",
    tips: [
      "Use an ovenproof handle and remember it stays hot after baking.",
      "If your pan is not ovenproof, transfer the vegetables to a greased baking dish first.",
    ],
  }),
  r({
    id: "stuffed-sweet-potatoes",
    name: "Black bean stuffed sweet potatoes",
    subtitle: "Soft baked potatoes with a lime-dressed bean filling.",
    cuisine: "Tex-Mex-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 50,
    ingredients: [
      ["Sweet potatoes", "4 medium", "Produce"],
      ["Black beans", "2 × 400 g cans", "Pantry"],
      ["Sweetcorn", "150 g", "Produce"],
      ["Tomatoes", "2", "Produce"],
      ["Avocados", "1", "Produce"],
      ["Limes", "1", "Produce"],
      ["Ground cumin", "1 tsp", "Pantry"],
      ["Olive oil", "1 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 210°C conventional or 190°C fan. Scrub sweet potatoes and prick several times with a fork.",
      "Rub with a little oil, place on a tray and bake for 45–55 minutes until a knife slides into the centre easily.",
      "Drain beans. Warm them in a saucepan with corn, cumin and 100 ml water for 8–10 minutes.",
      "Dice tomatoes and avocado. Toss with lime juice and a pinch of salt.",
      "Split each cooked potato lengthways and gently press the ends to open it.",
      "Spoon beans into the potatoes and top with tomato and avocado just before serving.",
    ],
    servingSuggestion: "Serve one potato per person with leafy salad.",
    tips: [
      "Choose potatoes of similar size so they finish together.",
      "Add a spoon of yoghurt if you prefer a creamy topping.",
    ],
  }),
  r({
    id: "chickpea-wraps",
    name: "Crunchy chickpea wraps",
    subtitle:
      "A quick lunch with smashed chickpeas, lemon and fresh vegetables.",
    cuisine: "Mediterranean-inspired",
    region,
    diet: "Plant-based",
    prepTime: 20,
    cookTime: 0,
    ingredients: [
      ["Cooked chickpeas", "2 × 400 g cans", "Pantry"],
      ["Large wraps", "4", "Bakery"],
      ["Tahini", "2 tbsp", "Pantry"],
      ["Lemons", "1", "Produce"],
      ["Cucumber", "½", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Lettuce", "4 large leaves", "Produce"],
      ["Ground cumin", "½ tsp", "Pantry"],
      ["Olive oil", "1 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Drain and rinse chickpeas, then mash roughly with a fork, leaving some texture.",
      "Whisk tahini, lemon juice, oil, cumin and 2 tablespoons water into a pourable dressing.",
      "Fold dressing into chickpeas and taste for salt. Add a little water if the filling is too stiff.",
      "Wash and dry lettuce, grate carrots and cut cucumber into thin sticks.",
      "Lay wraps flat. Add lettuce, vegetables and chickpea filling across the centre, keeping the edges clear.",
      "Fold in the sides, roll tightly from the bottom and cut in half to serve.",
    ],
    servingSuggestion: "Serve with fruit or extra vegetable sticks.",
    tips: [
      "Tahini contains sesame; plain yoghurt gives a different, non-vegan dressing.",
      "For packed lunches, keep the filling chilled and assemble near serving time.",
    ],
  }),
  r({
    id: "turkey-meatballs",
    name: "Turkey meatballs in tomato sauce",
    subtitle: "Tender baked meatballs with a simple pasta sauce.",
    cuisine: "Italian-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 20,
    cookTime: 30,
    ingredients: [
      ["Turkey mince", "500 g", "Meat & fish"],
      ["Eggs", "1", "Dairy & eggs"],
      ["Breadcrumbs", "50 g", "Pantry"],
      ["Spaghetti", "300 g", "Pantry"],
      ["Passata", "700 ml", "Pantry"],
      ["Onions", "1", "Produce"],
      ["Garlic", "3 cloves", "Produce"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
    ],
    steps: [
      "Heat oven to 210°C conventional or 190°C fan. Mix turkey, egg, breadcrumbs, one crushed garlic clove and salt gently.",
      "Shape into 16 small meatballs, place on an oiled tray and bake for 18–22 minutes until their centres reach 74°C.",
      "Meanwhile dice onion and soften in remaining oil for 5 minutes. Add remaining garlic and oregano for 1 minute.",
      "Pour in passata and 100 ml water. Simmer gently for 15 minutes and taste for seasoning.",
      "Cook spaghetti according to its packet, reserving a mug of cooking water before draining.",
      "Transfer cooked meatballs to the sauce. Serve over pasta, loosening the sauce with pasta water if needed.",
    ],
    servingSuggestion:
      "Serve four meatballs each, with steamed green vegetables.",
    tips: [
      "Mixing too firmly can make meatballs dense.",
      "Wet hands make shaping easier without extra flour.",
    ],
  }),
  r({
    id: "shepherds-pie",
    name: "Family shepherd’s pie",
    subtitle: "Lamb and vegetables under a golden mashed-potato lid.",
    cuisine: "British-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 25,
    cookTime: 50,
    ingredients: [
      ["Lamb mince", "500 g", "Meat & fish"],
      ["Potatoes", "900 g", "Produce"],
      ["Onions", "1", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Frozen peas", "150 g", "Produce"],
      ["Tomato paste", "2 tbsp", "Pantry"],
      ["Beef stock", "400 ml", "Pantry"],
      ["Plain flour", "1 tbsp", "Pantry"],
      ["Milk", "100 ml", "Dairy & eggs"],
      ["Butter", "30 g", "Dairy & eggs"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Peel and cube potatoes. Boil for 15–20 minutes until tender. Drain and mash with warm milk, butter and salt.",
      "Heat oven to 200°C conventional or 180°C fan. Dice onion and carrots.",
      "Brown lamb in oil for 6–8 minutes, breaking up clumps. Add onion and carrots and cook for 5 minutes.",
      "Stir in flour and tomato paste, then slowly add stock. Simmer for 15 minutes until thickened; stir in peas.",
      "Spoon filling into a baking dish and cover evenly with mash. Roughen the top with a fork.",
      "Bake for 25 minutes until golden and hot through to 74°C. Rest for 5 minutes before serving.",
    ],
    servingSuggestion: "Serve with steamed cabbage or broccoli.",
    tips: [
      "Using beef mince makes this a cottage pie.",
      "Let the filling thicken before adding mash so the topping stays on top.",
    ],
  }),
  r({
    id: "vegetable-noodles",
    name: "Rainbow vegetable noodles",
    subtitle: "Crisp vegetables and noodles in a ginger-soy dressing.",
    cuisine: "East Asian-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 15,
    ingredients: [
      ["Wheat noodles (egg-free)", "300 g", "Pantry"],
      ["Cabbage", "¼ small", "Produce"],
      ["Carrots", "2", "Produce"],
      ["Red peppers", "1", "Produce"],
      ["Frozen edamame (shelled)", "200 g", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Fresh ginger", "15 g", "Produce"],
      ["Soy sauce", "3 tbsp", "Pantry"],
      ["Rice vinegar", "1 tbsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Sesame oil", "1 tsp", "Pantry"],
    ],
    steps: [
      "Slice cabbage, carrots and pepper into thin strips. Mince garlic and grate ginger.",
      "Cook noodles according to their packet. Cook edamame as directed on its packet, then drain both.",
      "Heat vegetable oil in a large pan. Stir-fry carrots and pepper for 3 minutes, then add cabbage for 2 minutes.",
      "Add garlic and ginger and stir for 30 seconds. Pour in soy sauce, vinegar and 3 tablespoons water.",
      "Add noodles and edamame and toss with tongs for 2–3 minutes until everything is hot and coated.",
      "Drizzle with sesame oil, toss once more and divide between bowls.",
    ],
    servingSuggestion: "Serve immediately, with lime wedges if desired.",
    tips: [
      "Thin vegetables cook quickly without needing much water.",
      "Check noodles are egg-free for a plant-based meal.",
    ],
  }),
  r({
    id: "teriyaki-salmon",
    name: "Teriyaki-style salmon bowls",
    subtitle: "Sticky glazed salmon with rice and broccoli.",
    cuisine: "Japanese-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 10,
    cookTime: 25,
    ingredients: [
      ["Salmon fillets", "4 × 150 g", "Meat & fish"],
      ["Rice", "300 g", "Pantry"],
      ["Broccoli", "1 large head", "Produce"],
      ["Soy sauce", "3 tbsp", "Pantry"],
      ["Honey", "2 tbsp", "Pantry"],
      ["Rice vinegar", "1 tbsp", "Pantry"],
      ["Fresh ginger", "15 g", "Produce"],
      ["Garlic", "1 clove", "Produce"],
      ["Cornflour", "1 tsp", "Pantry"],
    ],
    steps: [
      "Heat oven to 200°C conventional or 180°C fan. Start rice cooking according to its packet.",
      "Mix soy sauce, honey, vinegar, grated ginger, crushed garlic, cornflour and 100 ml cold water in a small saucepan.",
      "Bring to a gentle bubble, stirring for 2 minutes until lightly thickened. Keep half the glaze separate for serving.",
      "Place salmon in a baking dish and brush with the other half. Bake for 12–18 minutes until the thickest part reaches 63°C.",
      "Meanwhile steam broccoli florets for 5–7 minutes until tender but still green.",
      "Divide rice, broccoli and salmon between bowls. Spoon over the reserved glaze.",
    ],
    servingSuggestion: "Add sliced cucumber or spring onions if available.",
    tips: [
      "Keep serving glaze separate from brushes that touch raw fish.",
      "Use maple syrup instead of honey if preferred.",
    ],
  }),
  r({
    id: "peanut-noodles",
    name: "Peanut & lime noodles",
    subtitle: "A creamy peanut sauce with crunchy vegetables and tofu.",
    cuisine: "Southeast Asian-inspired",
    region,
    diet: "Plant-based",
    prepTime: 15,
    cookTime: 15,
    ingredients: [
      ["Rice noodles", "300 g", "Pantry"],
      ["Firm tofu", "400 g", "Pantry"],
      ["Unsweetened peanut butter", "80 g", "Pantry"],
      ["Carrots", "2", "Produce"],
      ["Cucumber", "½", "Produce"],
      ["Soy sauce", "2 tbsp", "Pantry"],
      ["Limes", "2", "Produce"],
      ["Maple syrup", "1 tbsp", "Pantry"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
    ],
    steps: [
      "Pat tofu dry and cut into cubes. Peel carrots into ribbons and slice cucumber into thin sticks.",
      "Cook or soak rice noodles following the packet, then drain and rinse briefly if instructed.",
      "Heat oil in a non-stick pan and fry tofu for 8–10 minutes, turning until golden.",
      "Whisk peanut butter, soy sauce, lime juice, maple syrup and 120 ml warm water into a smooth dressing.",
      "Toss warm noodles with most of the dressing, then fold in tofu, carrot and cucumber.",
      "Add the remaining dressing or a splash of water to loosen and divide between bowls.",
    ],
    servingSuggestion: "Serve warm or cool, with extra lime wedges.",
    tips: [
      "Contains peanuts; this sauce is built around peanut butter.",
      "Different rice noodles need different soaking times, so use the packet directions.",
    ],
  }),
  r({
    id: "breakfast-burritos",
    name: "Egg & bean breakfast burritos",
    subtitle: "Warm wraps filled with eggs, beans and tomatoes.",
    cuisine: "Tex-Mex-inspired",
    region,
    diet: "Vegetarian",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      ["Large tortillas", "4", "Bakery"],
      ["Eggs", "6", "Dairy & eggs"],
      ["Black beans", "400 g can", "Pantry"],
      ["Tomatoes", "2", "Produce"],
      ["Cheddar cheese", "80 g", "Dairy & eggs"],
      ["Spring onions", "2", "Produce"],
      ["Ground cumin", "½ tsp", "Pantry"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Drain beans, dice tomatoes, slice spring onions and grate cheese.",
      "Warm beans in a small pan with cumin and 3 tablespoons water for 5 minutes.",
      "Beat eggs with a little salt. Heat oil in a non-stick pan and scramble the eggs gently until fully set.",
      "Warm tortillas in a dry pan for 20–30 seconds per side so they bend easily.",
      "Divide beans, eggs, tomatoes, onions and cheese across the centres of the tortillas.",
      "Fold sides inward and roll tightly. Return seam-side down to the dry pan for 1–2 minutes to lightly toast.",
    ],
    servingSuggestion: "Serve immediately with fruit or a little salsa.",
    tips: [
      "Drain the beans well so the wraps do not become soggy.",
      "Do not overfill; keep a clear border for folding.",
    ],
  }),
  r({
    id: "apple-porridge",
    name: "Apple & cinnamon porridge",
    subtitle: "Creamy warm oats with softly cooked apple.",
    cuisine: "Everyday favourites",
    region,
    diet: "Vegetarian",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 15,
    ingredients: [
      ["Rolled oats", "200 g", "Pantry"],
      ["Milk", "700 ml", "Dairy & eggs"],
      ["Apples", "2", "Produce"],
      ["Ground cinnamon", "1 tsp", "Pantry"],
      ["Raisins", "40 g", "Pantry"],
      ["Maple syrup", "1 tbsp, optional", "Pantry"],
    ],
    steps: [
      "Wash and core apples. Grate one and cut the other into small cubes.",
      "Put the diced apple in a small pan with 3 tablespoons water and half the cinnamon.",
      "Cover and cook on low for 8–10 minutes until soft, adding water if it dries out.",
      "Meanwhile put oats, milk, grated apple, raisins and remaining cinnamon in another saucepan.",
      "Bring to a gentle simmer and cook for 8–10 minutes, stirring often until creamy. Add extra milk or water if too thick.",
      "Divide into four bowls, top with the cooked apple and add optional maple syrup to taste.",
    ],
    servingSuggestion: "Serve warm with an extra splash of milk.",
    tips: [
      "Use oat or soy milk for a plant-based version.",
      "Raisins and apple add sweetness, so taste before adding syrup.",
    ],
  }),
  r({
    id: "yoghurt-granola-bowls",
    name: "Yoghurt & toasted oat bowls",
    subtitle: "Fruit and yoghurt with a freshly toasted oat topping.",
    cuisine: "Everyday favourites",
    region,
    diet: "Vegetarian",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 15,
    restTime: 10,
    restLabel: "Cool",
    ingredients: [
      ["Plain yoghurt", "600 g", "Dairy & eggs"],
      ["Rolled oats", "150 g", "Pantry"],
      ["Pumpkin seeds", "40 g", "Pantry"],
      ["Maple syrup", "2 tbsp", "Pantry"],
      ["Vegetable oil", "1 tbsp", "Pantry"],
      ["Ground cinnamon", "½ tsp", "Pantry"],
      ["Bananas", "2", "Produce"],
      ["Fresh berries", "200 g", "Produce"],
    ],
    steps: [
      "Heat oven to 170°C conventional or 150°C fan and line a baking tray.",
      "Mix oats, pumpkin seeds and cinnamon, then stir in oil and maple syrup until lightly coated.",
      "Spread thinly on the tray. Bake for 12–15 minutes, stirring halfway, until lightly golden.",
      "Cool for 10 minutes; the oat mixture becomes crisper as it cools.",
      "Divide yoghurt between four bowls. Slice bananas and wash and dry berries.",
      "Add fruit and the cooled toasted oats just before serving.",
    ],
    servingSuggestion: "Serve as breakfast or reduce portions for a snack.",
    tips: [
      "Keep the oat topping separate until serving to preserve the crunch.",
      "Use dairy-free yoghurt if preferred.",
    ],
  }),
  r({
    id: "vegetable-lasagne",
    name: "Roasted vegetable lasagne",
    subtitle: "Layers of tomato vegetables, pasta and creamy ricotta.",
    cuisine: "Italian-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 25,
    cookTime: 60,
    restTime: 10,
    restLabel: "Rest",
    servings: 6,
    ingredients: [
      ["No-pre-cook lasagne sheets", "250 g", "Pantry"],
      ["Courgettes", "2", "Produce"],
      ["Aubergine", "1", "Produce"],
      ["Red peppers", "2", "Produce"],
      ["Passata", "900 ml", "Pantry"],
      ["Ricotta", "400 g", "Dairy & eggs"],
      ["Mozzarella", "200 g", "Dairy & eggs"],
      ["Milk", "100 ml", "Dairy & eggs"],
      ["Garlic", "3 cloves", "Produce"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Dried oregano", "1 tsp", "Pantry"],
      ["Salt", "to taste", "Pantry"],
    ],
    steps: [
      "Heat oven to 220°C conventional or 200°C fan. Dice vegetables, toss with oil and roast on two trays for 20 minutes.",
      "Mix passata with crushed garlic, oregano and salt. Whisk ricotta with milk until spreadable.",
      "Reduce oven to 190°C conventional or 170°C fan. Spoon a little tomato sauce into a deep baking dish.",
      "Layer pasta sheets, vegetables, tomato sauce and ricotta three times, making sure all pasta edges are covered in sauce.",
      "Top with torn mozzarella. Cover with foil and bake for 25 minutes, then uncover for 15 minutes until golden, bubbling and 74°C in the centre.",
      "Check pasta is tender with a knife and rest for 10 minutes before slicing.",
    ],
    servingSuggestion:
      "Serves six with salad; choose vegetarian cheeses if needed.",
    tips: [
      "Use sheets labelled no-pre-cook; other pasta may need boiling first.",
      "Resting helps the layers hold together when cut.",
    ],
  }),
  r({
    id: "chicken-fajitas",
    name: "Chicken fajita wraps",
    subtitle: "Sizzling peppers and chicken ready for everyone to wrap.",
    cuisine: "Tex-Mex-inspired",
    region,
    diet: "Meat & fish",
    prepTime: 15,
    cookTime: 20,
    ingredients: [
      ["Chicken breast", "600 g", "Meat & fish"],
      ["Tortillas", "8 small", "Bakery"],
      ["Red peppers", "2", "Produce"],
      ["Onions", "1", "Produce"],
      ["Limes", "1", "Produce"],
      ["Ground cumin", "1 tsp", "Pantry"],
      ["Smoked paprika", "2 tsp", "Pantry"],
      ["Garlic powder", "1 tsp", "Pantry"],
      ["Vegetable oil", "2 tbsp", "Pantry"],
      ["Salt", "½ tsp", "Pantry"],
    ],
    steps: [
      "Slice chicken into thin strips and peppers and onion into similar-sized strips.",
      "Mix cumin, paprika, garlic powder, salt and half the oil. Toss through chicken.",
      "Heat a wide pan and cook chicken in batches for 6–8 minutes, turning, until it reaches 74°C. Transfer to a clean plate.",
      "Add remaining oil, peppers and onion to the pan. Cook for 6–8 minutes until softened with browned edges.",
      "Return chicken, squeeze in lime juice and toss for 1 minute until hot. Add a splash of water if spices stick.",
      "Warm tortillas in a dry pan or according to the packet and serve fillings separately for everyone to assemble.",
    ],
    servingSuggestion: "Offer avocado, yoghurt or salsa as optional toppings.",
    tips: [
      "Cook in batches if the pan is crowded.",
      "Cut strips evenly so no thick pieces remain undercooked.",
    ],
  }),
  r({
    id: "lemon-pea-orzo",
    name: "Lemon, pea & spinach orzo",
    subtitle: "A bright one-pot pasta with a creamy finish.",
    cuisine: "Mediterranean-inspired",
    region,
    diet: "Vegetarian",
    prepTime: 10,
    cookTime: 20,
    ingredients: [
      ["Orzo", "300 g", "Pantry"],
      ["Frozen peas", "200 g", "Produce"],
      ["Spinach", "150 g", "Produce"],
      ["Onions", "1", "Produce"],
      ["Garlic", "2 cloves", "Produce"],
      ["Vegetable stock", "900 ml", "Pantry"],
      ["Lemons", "1", "Produce"],
      ["Vegetarian hard cheese", "50 g", "Dairy & eggs"],
      ["Olive oil", "2 tbsp", "Pantry"],
      ["Black pepper", "¼ tsp", "Pantry"],
    ],
    steps: [
      "Dice onion, mince garlic and zest the lemon. Heat oil in a wide saucepan.",
      "Soften onion for 5 minutes, add garlic for 1 minute and stir in orzo to coat.",
      "Pour in hot stock and bring to a gentle simmer. Cook for 8–10 minutes, stirring frequently so the pasta does not stick.",
      "Add peas and cook for another 3–4 minutes, until the orzo is tender. Add extra hot water if needed.",
      "Fold in spinach, grated cheese, lemon zest and pepper. Stir until spinach wilts.",
      "Add lemon juice to taste and enough water to keep it creamy. Serve immediately.",
    ],
    servingSuggestion:
      "Serve with a tomato salad; this is filling enough as a main.",
    tips: [
      "Orzo is pasta, so it contains wheat.",
      "It thickens as it stands; loosen with a splash of hot water before serving.",
    ],
  }),
];
