// Regenerates the database's copy of the planner JSON schema from src/lib/data.ts.
// Run after changing the data model: npm run db:schema
// Then re-run supabase/schema.sql in the Supabase SQL editor.
import { readFileSync, writeFileSync } from "node:fs";
import { plannerJsonSchema } from "../src/lib/json-schema";
import { recipes } from "../src/lib/data";

const json = JSON.stringify(plannerJsonSchema());
writeFileSync(
  "supabase/planner.schema.json",
  JSON.stringify(plannerJsonSchema(), null, 2) + "\n",
);
let sql = readFileSync("supabase/schema.sql", "utf8");
const recipeRule = /item->>'recipeId' not in \([^)]*\)/;
if (!recipeRule.test(sql))
  throw new Error("Recipe allowlist not found in schema.sql");
if (recipes.some((recipe) => !/^[a-z0-9-]+$/.test(recipe.id)))
  throw new Error("Recipe IDs must be safe SQL literals");
sql = sql.replace(
  recipeRule,
  `item->>'recipeId' not in (${recipes.map((recipe) => `'${recipe.id}'`).join(",")})`,
);
const marker = /\$schema\$[\s\S]*?\$schema\$/;
if (!marker.test(sql)) throw new Error("No $schema$ block found in schema.sql");
writeFileSync(
  "supabase/schema.sql",
  sql.replace(marker, () => `$schema$${json}$schema$`),
);
// A smaller, repeatable update for families that already ran the full setup.
const updatedSql = readFileSync("supabase/schema.sql", "utf8");
const validationFunction = updatedSql.match(
  /create or replace function public\.planner_validate_data[\s\S]*?\n\$\$;/,
)?.[0];
if (!validationFunction) throw new Error("Data validation function not found");
writeFileSync(
  "supabase/update-recipes.sql",
  [
    "-- Generated by npm run db:schema. Run in the existing project's SQL Editor.",
    "-- Updates validation for the recipe library; leaves family plans and access unchanged.",
    "begin;",
    validationFunction,
    "revoke all on function public.planner_validate_data(jsonb) from public, anon, authenticated;",
    "notify pgrst, 'reload schema';",
    "commit;",
    "",
  ].join("\n\n"),
);
console.log(
  "Updated planner schema, recipe allowlist and supabase/update-recipes.sql",
);
